version: '3.9'
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    working_dir: /app
    volumes:
      - ./frontend/vue-practice:/app
    ports:
      - 5173:5173
    tty: true
    stdin_open: true
